name: test

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    name: Build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn build
  test_bbs:
    name: Test BBS
    runs-on: ${{matrix.os}}
    env:
      TEST_SIGNATURE_SCHEME: 'BBS'
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn test
  test_bbs_plus:
    name: Test BBS+
    runs-on: ${{matrix.os}}
    env:
      TEST_SIGNATURE_SCHEME: 'BBS+'
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn test
  test_ps:
    name: Test PS
    runs-on: ${{matrix.os}}
    env:
      TEST_SIGNATURE_SCHEME: 'PS'
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn test
  test_bbdt16:
    name: Test BBDT16
    runs-on: ${{matrix.os}}
    env:
      TEST_SIGNATURE_SCHEME: 'BBDT16'
    strategy:
      matrix:
        node-version: [18.x, 20.x ]
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn test